### ISSUE TITLE
Delay in login, need to press twice to enter application

### ISSUE THREAD

**Issue by USabah** [Temper-Tunes-Senior-Design-Project/TemperTunes#33]
Occasionally when I press the login button, I need to press it again to access the app. 

Also, since there's a bit of a delay when the login button is pressed, the button can be spammed (maybe add a loading indicator for this).

**Comment by dtleight** [comment]
Fixed in the latest auth pr. The button can still be spammed with a minor delay between page loads but this has no adverse effects.
